# Generated by Django 4.1.4 on 2022-12-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='information',
        ),
    ]
